apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 360000"]
    volumeMounts:
    - name: metrics-pvc
      mountPath: /app/io/
  volumes:
  - name: metrics-pvc
    persistentVolumeClaim:
      claimName: metricspvc
