# Runtime config
period: January24-May25
ingest:
  run:
    - PromQLIngestController
    - IngestTimeline
analysis:
  run:
    - verifycpuhours
    - verifygpuhours
    - viscpuhoursmeta
    - visgpuhoursmeta
    - viscvgpuhours
saving:
  base-path: "./io/alltimegraphs_latest"
  exit-action: opendir
  run:
    - AnalysisSaver
    - VizualizationsSaver
    - SummarySaver

# Plugin-specific config sections
PromQLIngestController:
  main-periods: true
  query-cfgs:
    - monthly
AvailableHoursDriver:
  # Information about hardware configurations for each node.
  default:
    rci-tide-cpu:
      cpu: 64
      gpu: 4
      node_cnt: 6
    rci-tide-gpu:  # Targets L40 GPUs
      cpu: 24
      gpu: 4
      node_cnt: 17
    rci-nrp-gpu:  # Targets A100 GPUs
      cpu: 64
      gpu: 4
      node_cnt: 8