base_url: "https://thanos.nrp-nautilus.io/api/v1/query_range"
step: 3600
queries: 
    status: |
        kube_pod_status_phase{
            phase="Running",
            namespace=~"csusb.*|csu.*|cal-poly-.*|sdsu-.*|csun-.*|nsf-maica",
            namespace!~"sdsu-jupyterhub.*"
        }
    truth: |
        kube_pod_container_resource_requests{
            namespace=~"csusb.*|csu.*|cal-poly-.*|sdsu-.*|csun-.*|nsf-maica",
            namespace!~"sdsu-jupyterhub.*",
            resource = "%TYPE_STRING%",
            node=~"rci-tide.*",
            node!~"rci-tide-dtn.*"
        }
top5hours_blacklist:
  - sdsu-rci-jh
  - csu-tide-jupyterhub
  - csusb-jupyterhub