base_url: "https://thanos.nrp-nautilus.io/api/v1/query_range"
step: 3600
queries: 
    status: |
        kube_pod_status_phase{
            phase="Running"
        }
    truth: |
        kube_pod_container_resource_requests{
          resource = "%TYPE_STRING%",
          node=~"rci-tide-gpu-0[7-9].*|rci-tide-gpu-1[0-7].*|rci-tide-cpu-06.sdsu.edu",
          namespace!~"nsf-maica|admiralty|argo|authentik|cdi|clockwork|coder|coturn|cvmfs-csi|dask-operator|default|drawio|elastic-system|elastiflow|envoy-ai-gateway-system|envoy-gateway-system|etherpad|falco|gatekeeper-system|gitlab|gpu-mon|guacamole|haproxy|hedgedoc|igrok-elastic|ipmi|job-admission|juice|jupyterlab|jupyterlab-east|keda-operator|kube-system|kubeflow|kubevirt|mad-movie|maddy|matrix-synapse|metallb-system|monitoring|mpi-operator|nebula-operator-system|netbox-4|netbox-agent|nextcloud|node-feature-discovery|node-problem-detector|nrp-security|olm|overleaf|perfsonar|piraeus-datastore|postgres-operator|ray|resource-email|rook|rook-central|rook-east|rook-fullerton|rook-haosu|rook-pacific|rook-south-east|rook-system|rook-tide|rook-ucsd|scylla-operator|sealed-secrets-operator|smartctl-exporter|smarter-device-manager|spegel|stirling-pdf|syncthing|system-test|token-manager|unikorn"
        }
top5hours_blacklist:
  - sdsu-rci-jh
  - csu-tide-jupyterhub
  - csusb-jupyterhub