# Runtime config
period: ytd
timeline:
  sub_period_max_len: 302400 # Half a week
ingest:
  run:
    - PromQLIngestController
    - IngestTimeline
analysis:
  run:
    - verifycpuhours
    - verifygpuhours
    - tidesplitmeta
saving:
  base-path: "./io/tidesplit_latest"
  run:
    - AnalysisSaver
    - VizualizationsSaver

# Plugin-specific config sections
PromQLIngestController:
  main-periossds: false
  query-cfgs:
    - csu
    - non-csu
    - tainted
    - untainted
AvailableHoursDriver:
  # Information about hardware configurations for each node.
  default:
    rci-tide-cpu:
      cpu: 64
      gpu: 4
      node_cnt: 6
    rci-tide-gpu:  # Targets L40 GPUs
      cpu: 24
      gpu: 4
      node_cnt: 17
    rci-nrp-gpu:  # Targets A100 GPUs
      cpu: 64
      gpu: 4
      node_cnt: 8
  tainted:
    rci-tide-cpu:
      cpu: 64
      gpu: 4
      node_cnt: 1
    rci-tide-gpu:
      cpu: 24
      gpu: 4
      node_cnt: 11
    rci-nrp-gpu:
      cpu: 64
      gpu: 4
      node_cnt: 8
  untainted:
    rci-tide-cpu:
      cpu: 64
      gpu: 4
      node_cnt: 5
    rci-tide-gpu:
      cpu: 24
      gpu: 4
      node_cnt: 6
    rci-nrp-gpu:
      cpu: 64
      gpu: 4
      node_cnt: 8
AnalysisSaver:
  whitelist:
    - tidesplitmeta
