# Runtime config
period: ytd-lastmonth
ingest:
  run:
    - PromQLIngestController
    - IngestTimeline
analysis:
  run:
    - viscvgpuhours
    - viscpuhoursmeta
    - visgpuhoursmeta
saving:
  base-path: "./io/ytdcpu_latest"
  exit-action: opendir
  run:
    - VizualizationsSaver

# Plugin-specific config sections
PromQLIngestController:
  main-periods: true
  query-cfgs:
    - tainted
AvailableHoursDriver:
  # Information about hardware configurations for each node.
  default:
    rci-tide-cpu:
      cpu: 64
      gpu: 4
      node_cnt: 6
    rci-tide-gpu:  # Targets L40 GPUs
      cpu: 24
      gpu: 4
      node_cnt: 17
    rci-nrp-gpu:  # Targets A100 GPUs
      cpu: 64
      gpu: 4
      node_cnt: 8